spring.application.name=app

# Use wildcard to expose all endpoints = "*"
# Can also expose individual endpoints by comma-separated list, e.g. "health,info"
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My App
info.app.description=This is a sample Spring Boot application.
info.app.version=1.0.0